export const grondTourFacts = [
  'Canada has the longest coastline in the world.',
  'The country has more lakes than all other nations combined.',
  'The maple leaf has been a national symbol for over 150 years.',
  'Canadians consume more macaroni and cheese than any other country.',
  'Toronto is one of the world’s most multicultural cities.',
  'Canada’s national parks are larger than some countries.',
  'The Bay of Fundy has the highest tides on Earth.',
  'Hockey and lacrosse are Canada’s official national sports.',
  'Canada has two official languages: English and French.',
  'Nunavut is the largest and newest territory, created in 1999.',
  'The CN Tower held the world height record for over 30 years.',
  'Canada produces over 70% of the world’s maple syrup.',
  'Polar bears outnumber people in some northern towns.',
  'Alberta’s Badlands hold many dinosaur fossils.',
  'Montreal is the second-largest French-speaking city after Paris.',
  'Canada has one of the world’s strongest passport rankings.',
  'The Trans-Canada Highway is one of the longest on Earth.',
  'Canadians invented the snowmobile.',
  'The Northern Lights can be seen from many provinces and territories.',
];
